version: '3.3'

services:
  ubuntu-test: #サービス名はdevcontainer.jsonのサービス名と合わせる。
    image: ubuntu
    tty: true # これをしないとコンテナが起動し続けないのでエラーになる。
    working_dir: /work # これをしないとworkフォルダがないのでエラーになる。
    volumes: 
      - ../work:/work # ファイル共有